export const ACTION_STORE_NEW_POKEMONS = 'ACTION_STORE_NEW_POKEMONS';
export const ACTION_ADD_NEW_POKEMON_DATA = 'ACTION_ADD_NEW_POKEMON_DATA';
export const ACTION_ANOTHER_ACTION = 'ACTION_ANOTHER_ACTION';
