export const ACTION_ADD_NEW_POKEMON_DATA = 'ACTION_ADD_NEW_POKEMON_DATA';
export const ACTION_ADD_NEW_POKEMON_SPECIES_DATA =
  'ACTION_ADD_NEW_POKEMON_SPECIES_DATA';
export const ACTION_SET_META_LIMIT = 'ACTION_SET_META_LIMIT';
export const ACTION_ADD_NEW_ABILITY_DATA = 'ACTION_ADD_NEW_ABILITY_DATA';
